// SPDX-License-Identifier: GPL-3.0-or-later

package `in`.orbitmaps.app.routing

import `in`.orbitmaps.core.model.LatLon
import java.io.File
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray
import kotlinx.serialization.json.putJsonObject

/** Travel modes, as Valhalla "costing" names. */
enum class Costing(val valhallaName: String) {
    Car("auto"),
    Bike("bicycle"),
    Walk("pedestrian")
}

/** The parts of a Valhalla route the app needs. [shape] is the route line, for the trip corridor. */
data class RouteSummary(
    val lengthKm: Double,
    val timeSeconds: Double,
    val maneuvers: Int,
    val shape: List<LatLon> = emptyList()
)

/** Valhalla answered with an error, e.g. no road near a point (code 171) or no route (442). */
class RoutingException(message: String) : Exception(message)

/**
 * Builds and reads the JSON that Valhalla takes and returns. Pure functions, so they are unit-tested
 * without the native engine.
 */
object ValhallaJson {
    /** Where the tile build mounts its work directory; paths in the generated config start here. */
    const val BUILD_DATA_DIR = "/data/"

    private val json = Json { ignoreUnknownKeys = true }

    /**
     * Turns the config generated by the tile build into one for this device: `mjolnir.tile_extract`
     * points at the installed tar, and every other path from the build (tile dir, admin and timezone
     * databases, traffic extract) moves under [dataDir]. Those files don't exist on the phone, and
     * routing doesn't need them.
     */
    fun deviceConfig(template: String, tileExtract: File, dataDir: File): String {
        val root = json.parseToJsonElement(template).jsonObject
        val rewritten = rewritePaths(root, dataDir.absolutePath.trimEnd('/') + "/") as JsonObject
        val mjolnir = requireNotNull(rewritten["mjolnir"]?.jsonObject) { "config has no mjolnir section" }
        val withTar = JsonObject(mjolnir + ("tile_extract" to JsonPrimitive(tileExtract.absolutePath)))
        return JsonObject(rewritten + ("mjolnir" to withTar)).toString()
    }

    /**
     * A config that reads tiles from a folder ([tileDir], Valhalla's tile_dir layout) instead of one tar,
     * for tiles downloaded on demand. Other build paths move under [dataDir], as in [deviceConfig].
     */
    fun tileDirConfig(template: String, tileDir: File, dataDir: File): String {
        val root = json.parseToJsonElement(template).jsonObject
        val rewritten = rewritePaths(root, dataDir.absolutePath.trimEnd('/') + "/") as JsonObject
        val mjolnir = requireNotNull(rewritten["mjolnir"]?.jsonObject) { "config has no mjolnir section" }
        val withDir = JsonObject(
            mjolnir - "tile_extract" - "traffic_extract" + ("tile_dir" to JsonPrimitive(tileDir.absolutePath))
        )
        return JsonObject(rewritten + ("mjolnir" to withDir)).toString()
    }

    private fun rewritePaths(element: JsonElement, deviceDir: String): JsonElement = when (element) {
        is JsonObject -> JsonObject(element.mapValues { (_, value) -> rewritePaths(value, deviceDir) })
        is JsonArray -> JsonArray(element.map { rewritePaths(it, deviceDir) })
        is JsonPrimitive -> {
            val text = if (element.isString) element.contentOrNull else null
            if (text != null && text.startsWith(BUILD_DATA_DIR)) {
                JsonPrimitive(deviceDir + text.removePrefix(BUILD_DATA_DIR))
            } else {
                element
            }
        }
    }

    /** A route request between two points. Instructions are included, as navigation will need them. */
    fun routeRequest(from: LatLon, to: LatLon, costing: Costing = Costing.Car): String = buildJsonObject {
        putJsonArray("locations") {
            add(location(from))
            add(location(to))
        }
        put("costing", costing.valhallaName)
        putJsonObject("directions_options") { put("units", "kilometers") }
    }.toString()

    private fun location(point: LatLon) = buildJsonObject {
        put("lat", point.latitude)
        put("lon", point.longitude)
    }

    /** Reads `trip.summary` and counts the maneuvers, or throws [RoutingException] for an error reply. */
    fun parseRoute(response: String): RouteSummary {
        val root = json.parseToJsonElement(response).jsonObject
        root["error"]?.let { error ->
            val code = root["error_code"]?.jsonPrimitive?.contentOrNull
            throw RoutingException(listOfNotNull(code, error.jsonPrimitive.contentOrNull).joinToString(": "))
        }
        val trip = root["trip"]?.jsonObject ?: throw RoutingException("response has no trip")
        val summary = trip["summary"]?.jsonObject ?: throw RoutingException("trip has no summary")
        val legs = (trip["legs"] as? JsonArray).orEmpty().map { it.jsonObject }
        val maneuvers = legs.sumOf { leg -> (leg["maneuvers"] as? JsonArray)?.size ?: 0 }
        val shape = try {
            legs.flatMap { leg -> leg["shape"]?.jsonPrimitive?.contentOrNull?.let(Polyline6::decode).orEmpty() }
        } catch (e: IllegalArgumentException) {
            throw RoutingException("route shape is malformed")
        }
        return RouteSummary(
            lengthKm = summary.number("length"),
            timeSeconds = summary.number("time"),
            maneuvers = maneuvers,
            shape = shape
        )
    }

    private fun JsonObject.number(key: String): Double =
        this[key]?.jsonPrimitive?.doubleOrNull ?: throw RoutingException("summary has no $key")

    private fun JsonArray?.orEmpty(): List<JsonElement> = this ?: emptyList()
}
