// SPDX-License-Identifier: GPL-3.0-or-later

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "in.orbitmaps.app"
    compileSdk = 37

    defaultConfig {
        applicationId = "in.orbitmaps.app"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "0.0.1"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    sourceSets {
        getByName("main") {
            // Offline map style, glyphs and sprites (asset://map/...), generated by pipeline/style.
            assets.directories.add(rootProject.file("styles/bundled").path)
        }
    }

    lint {
        abortOnError = true
        warningsAsErrors = true
        checkDependencies = true
        error += "HardcodedText"
        // These checks depend on what is published online, which makes CI results change over time.
        // Dependency updates are handled separately.
        disable += setOf("GradleDependency", "NewerVersionAvailable", "AndroidGradlePluginVersion", "OldTargetApi")
    }

    dependenciesInfo {
        // Don't embed the dependency metadata block that only Google Play can read (F-Droid rejects it).
        includeInApk = false
        includeInBundle = false
    }
}

dependencies {
    implementation(project(":core:model"))

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.ui)

    testImplementation(libs.junit)
}
