// SPDX-License-Identifier: GPL-3.0-or-later

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

val sampleRegionAssets = rootProject.file("pipeline/out/sample-region/assets")
if (!sampleRegionAssets.resolve("regions/panaji.pmtiles").isFile) {
    logger.warn(
        "Sample region not found: debug builds will show 'no region installed'. " +
            "Run: python -I pipeline/sample_region/fetch_sample_region.py"
    )
}

android {
    namespace = "in.orbitmaps.app"
    compileSdk = 37

    defaultConfig {
        applicationId = "in.orbitmaps.app"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "0.0.1"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    sourceSets {
        getByName("main") {
            // Offline map style, glyphs and sprites (asset://map/...), generated by pipeline/style.
            assets.directories.add(rootProject.file("styles/bundled").path)
        }
        getByName("debug") {
            // The sample region (regions/panaji.pmtiles) ships in debug builds only.
            assets.directories.add(sampleRegionAssets.path)
        }
    }

    androidResources {
        // PMTiles tiles are already compressed; storing the archive as-is saves work at build and install.
        noCompress += "pmtiles"
    }

    lint {
        abortOnError = true
        warningsAsErrors = true
        checkDependencies = true
        error += "HardcodedText"
        // These checks depend on what is published online, which makes CI results change over time.
        // Dependency updates are handled separately.
        disable += setOf("GradleDependency", "NewerVersionAvailable", "AndroidGradlePluginVersion", "OldTargetApi")
    }

    testOptions {
        unitTests.all { test ->
            // Unit tests read the real bundled style and string resources.
            val stylesDir = rootProject.file("styles/bundled")
            val resDir = file("src/main/res")
            test.inputs.dir(stylesDir).withPathSensitivity(PathSensitivity.RELATIVE)
            test.inputs.dir(resDir).withPathSensitivity(PathSensitivity.RELATIVE)
            test.systemProperty("orbitmaps.stylesDir", stylesDir.path)
            test.systemProperty("orbitmaps.resDir", resDir.path)
        }
    }

    dependenciesInfo {
        // Don't embed the dependency metadata block that only Google Play can read (F-Droid rejects it).
        includeInApk = false
        includeInBundle = false
    }
}

dependencies {
    implementation(project(":core:model"))

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.material.icons.core)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.maplibre.android)
    implementation(libs.valhalla.mobile)

    // Renders @Preview composables in Android Studio; debug builds only.
    debugImplementation(libs.androidx.compose.ui.tooling)

    testImplementation(libs.junit)
}
